import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import {
  BotMessageSquare, FileText, ChevronRight, Target,
  TrendingUp, AlertTriangle, Lightbulb, Loader2, Download,
} from "lucide-react";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

export default function Coaching() {
  const queryClient = useQueryClient();
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Persist report in React Query cache (survives tab switches)
  const report = queryClient.getQueryData<any>(["coaching-report"]) ?? null;

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);

    try {
      const result = await api.generateReport();
      queryClient.setQueryData(["coaching-report"], result);
    } catch (e: any) {
      setError(e.message || "코칭 생성 실패");
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;

    const text = [
      "═══════════════════════════════════════",
      "  bitcoach AI 코칭 리포트",
      `  ${report.trade_count}건 분석`,
      "═══════════════════════════════════════",
      "",
      "▶ 요약",
      report.summary,
      "",
      "▶ 강점",
      report.strengths,
      "",
      "▶ 약점",
      report.weaknesses,
      "",
      "▶ 개선 제안",
      report.suggestions,
      "",
      "▶ 액션 아이템",
      ...(report.action_items || []).map(
        (item: any, i: number) =>
          `  ${i + 1}. [${item.priority}] ${item.action}\n     측정: ${item.metric}\n     기한: ${item.timeframe}`
      ),
      "",
      "───────────────────────────────────────",
      "Generated by bitcoach · github.com/11e3/bitcoach",
    ].join("\n");

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bitcoach-coaching-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const sections = report
    ? [
        { icon: FileText, label: "요약", content: report.summary, color: "text-brand-600", bg: "bg-brand-50" },
        { icon: TrendingUp, label: "강점", content: report.strengths, color: "text-green-600", bg: "bg-green-50" },
        { icon: AlertTriangle, label: "약점", content: report.weaknesses, color: "text-red-600", bg: "bg-red-50" },
        { icon: Lightbulb, label: "개선 제안", content: report.suggestions, color: "text-amber-600", bg: "bg-amber-50" },
      ]
    : [];

  const priorityColors: Record<string, string> = {
    high: "border-red-200 bg-red-50 text-red-700",
    medium: "border-amber-200 bg-amber-50 text-amber-700",
    low: "border-green-200 bg-green-50 text-green-700",
  };

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">AI 코칭</h1>
        <div className="flex gap-2">
          {report && (
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-2 rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
            >
              <Download className="h-4 w-4" />
              다운로드
            </button>
          )}
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-brand-700 disabled:opacity-50"
          >
            {generating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <BotMessageSquare className="h-4 w-4" />
            )}
            {generating ? "분석 중..." : report ? "다시 생성" : "리포트 생성"}
          </button>
        </div>
      </div>

      {/* Pipeline */}
      <div className="mb-6 flex items-center gap-2 overflow-x-auto rounded-lg border border-gray-100 bg-gray-50 px-4 py-3">
        {["분류 (Haiku)", "통계 (Python)", "패턴 (Haiku)", "코칭 (Haiku)", "액션 (Haiku)"].map(
          (step, i) => (
            <span key={step} className="flex shrink-0 items-center gap-1.5 text-xs text-gray-500">
              {i > 0 && <ChevronRight className="h-3 w-3 text-gray-300" />}
              <span className={cn(
                "rounded-full px-2.5 py-1 font-medium",
                step.includes("Python") ? "bg-amber-100 text-amber-700" : "bg-blue-100 text-blue-700"
              )}>
                {step}
              </span>
            </span>
          )
        )}
      </div>

      {/* Error */}
      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Empty state */}
      {!report && !generating && (
        <div className="flex h-48 flex-col items-center justify-center text-center">
          <BotMessageSquare className="mb-4 h-12 w-12 text-gray-300" />
          <p className="mb-2 text-lg font-semibold text-gray-600">
            AI 코칭 리포트를 생성하세요
          </p>
          <p className="text-sm text-gray-400">
            LangGraph 5단계 파이프라인이 거래 패턴을 분석합니다
          </p>
        </div>
      )}

      {/* Generating */}
      {generating && (
        <div className="flex h-48 flex-col items-center justify-center text-center">
          <Loader2 className="mb-4 h-10 w-10 animate-spin text-brand-500" />
          <p className="text-sm text-gray-500">
            5단계 파이프라인 실행 중... (30초~1분 소요)
          </p>
        </div>
      )}

      {/* Report */}
      {report && !generating && (
        <>
          <div className="mb-4 text-xs text-gray-400">
            {report.trade_count}건 분석
            {report.period_start && report.period_end && (
              <> · {report.period_start.slice(0, 10)} ~ {report.period_end.slice(0, 10)}</>
            )}
          </div>

          <div className="mb-8 space-y-4">
            {sections.map(({ icon: Icon, label, content, color, bg }) => (
              <div key={label} className="rounded-xl border border-gray-100 bg-white shadow-sm">
                <div className={cn("flex items-center gap-2 rounded-t-xl px-5 py-3", bg)}>
                  <Icon className={cn("h-4 w-4", color)} />
                  <span className={cn("text-sm font-semibold", color)}>{label}</span>
                </div>
                <div className="px-5 py-4">
                  <p className="whitespace-pre-wrap text-sm leading-relaxed text-gray-700">
                    {content || "데이터 없음"}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {report.action_items?.length > 0 && (
            <div>
              <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-gray-700">
                <Target className="h-4 w-4 text-brand-600" />
                액션 아이템
              </h3>
              <div className="space-y-3">
                {report.action_items.map((item: any, i: number) => (
                  <div
                    key={i}
                    className={cn(
                      "rounded-lg border p-4",
                      priorityColors[item.priority] || "border-gray-200 bg-gray-50"
                    )}
                  >
                    <div className="mb-1 flex items-start justify-between">
                      <p className="text-sm font-medium">{item.action}</p>
                      <span className="ml-2 shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase">
                        {item.priority}
                      </span>
                    </div>
                    <div className="mt-2 flex gap-4 text-xs opacity-75">
                      <span>측정: {item.metric}</span>
                      <span>기한: {item.timeframe}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
